title: QTM385
author: HaoqiGu
email: haoqi.gu@emory.edu
description: > # this means to ignore newlines until "baseurl:"
  thank you for coming

# social links
wechat: 15262807426
ins:  haoqigu

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
